name: Preview Deploy

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}-deploy-preview
  cancel-in-progress: true

jobs:
  deploy:
    name: Preview Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: npm ci

      - name: Build App
        run: npm run build:staging -- --base=/preview/${{ github.event.number }}/

      - name: AWS Deploy Preview
        if: success()
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: cgteam
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_PREVIEW_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_PREVIEW_SECRET }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'build'
          DEST_DIR: preview/${{ github.event.number }}

  set_comment:
    name: Set PR Comment
    needs: ['deploy']
    runs-on: self-hosted
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - name: Set Preview Link
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview
          message: ':gem: Teams App preview deployed to <http://cgteam.s3-website.eu-central-1.amazonaws.com/preview/${{ github.event.number }}>'
