name: Storybook Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-storybook
  cancel-in-progress: true

jobs:
  deploy_storybook:
    name: Storybook Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install 🔧
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy
        if: success()
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: cgteam
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_PREVIEW_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_PREVIEW_SECRET }}
          AWS_REGION: "eu-central-1"
          SOURCE_DIR: "storybook-static"
          DEST_DIR: stories
