name: Preview Storybook Deploy

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}-deploy-storybook-preview
  cancel-in-progress: true

jobs:
  deploy_storybook:
    name: Preview Storybook Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install 🔧
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy
        if: success()
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: cgteam
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_PREVIEW_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_PREVIEW_SECRET }}
          AWS_REGION: "eu-central-1"
          SOURCE_DIR: "storybook-static"
          DEST_DIR: stories/preview/${{ github.event.number }}

  set_comment:
    name: Set PR Comment
    needs: [ 'deploy_storybook' ]
    runs-on: self-hosted
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - name: Set Preview Link
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: storybook
          message: ":open_book: Teams Storybook preview deployed to <http://cgteam.s3-website.eu-central-1.amazonaws.com/stories/preview/${{ github.event.number }}>"
